server:
  port: 8761

eureka:
  instance:
    hostname: eureka1
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/
      #表示是否注册自身到eureka服务器
      #register-with-eureka: false
      #是否从eureka上获取注册信息
      #fetch-registry: false
  server:
    enable-self-preservation: false

spring:
  application:
    name: eureka
