
server:
  port: 9010
spring:
  application:
    name: invest
  jpa:
      generate-ddl: false
      show-sql: true
      hibernate:
        ddl-auto: none
  datasource:
    url: jdbc:mysql://39.106.10.102:3306/dtest1?useUnicode=true&amp;characterEncoding=UTF8
    data-username: zkbc
    data-password: password
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
         host: localhost
         port: 5672
         username: guest
         password: guest

feign:
  hystrix:
    enabled: true
evn:
  test3



