
Skip to content
This repository

    Pull requests
    Issues
    Marketplace
    Explore

    @limaoyin

1
0

    0

limaoyin/lmy
Code
Issues 0
Pull requests 0
Projects 0
Wiki
Insights
Settings
lmy/invest.yml
85a44a3 21 minutes ago
@limaoyin limaoyin Update invest.yml
33 lines (27 sloc) 645 Bytes
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
server:
  port: 9010
spring:
  application:
    name: xycinvest
  jpa:
      generate-ddl: false
      show-sql: true
      hibernate:
        ddl-auto: none
  datasource:
    url: jdbc:mysql://39.106.10.102:3306/dtest1?useUnicode=true&amp;characterEncoding=UTF8
    data-username: zkbc
    data-password: password
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
         host: localhost
         port: 5672
         username: guest
         password: guest

feign:
  hystrix:
    enabled: true

 
