eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9090
spring:
  application:
    name: xycconfig
  cloud:
    config:
      server:
        git:
          uri: https://github.com/limaoyin/xyconfig
          username: 1013127768@qq.com
          password: li6918222
          basedir: /Users/lmy/Desktop/cloud/xycc
