spring:
  application:
    name: reward
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: zkbc
    password: password
    url: jdbc:mysql://39.106.10.102:3306/test1?useUnicode=true&amp;characterEncoding=UTF8
    
    
    
    
