eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9020
spring:
  application:
    name: xycuser

#datasource config
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.100.103:3308/dtest1?useUnicode=true&amp;characterEncoding=UTF8
  username: zkbc
  password: password

#mybatis config
mybatis:
  typeAliasesPackage: com.xyc.user.model
  mapperLocations: classpath:../dao/*.xml
