eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9030
spring:
  application:
    name: xyczuul
zuul:
  routes:
    i:
      path: /i/**
      serviceId: invest
    u:
      path: /u/**
      serviceId: user
    r:
      path: /r/**
      serviceId: reward  
