

spring:
  application:
    name: zuul
zuul:
  routes:
    i:
      path: /i/**
      serviceId: invest
    u:
      path: /u/**
      serviceId: user
    r:
      path: /r/**
      serviceId: reward
      
